[project]
name = "galt-python-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "nuitka>=2.7.7",
    "pytest>=8.4.0",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.11.13",
]
